# Generated by Django 2.2.12 on 2022-12-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=200, null=True)),
                ('student_name', models.CharField(max_length=200, null=True)),
                ('student_contact', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
